// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-_ignWjW0I70fR-MeSGcmIBe9BlKD48',
    appId: '1:19284872025:web:c76dd88734f8ca95e8da48',
    messagingSenderId: '19284872025',
    projectId: 'fasum-filbert',
    authDomain: 'fasum-filbert.firebaseapp.com',
    storageBucket: 'fasum-filbert.firebasestorage.app',
    measurementId: 'G-RB6QMCFC6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwi9bY_kp5GQB85SVxh6gYazS8LG2jgzo',
    appId: '1:19284872025:android:2b2601ca1de0066ce8da48',
    messagingSenderId: '19284872025',
    projectId: 'fasum-filbert',
    storageBucket: 'fasum-filbert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB75o9e22SZ3kov2OxaRgcGZVpDvhmk_T4',
    appId: '1:19284872025:ios:e439dcecc813db51e8da48',
    messagingSenderId: '19284872025',
    projectId: 'fasum-filbert',
    storageBucket: 'fasum-filbert.firebasestorage.app',
    iosBundleId: 'com.example.fasumFilbert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB75o9e22SZ3kov2OxaRgcGZVpDvhmk_T4',
    appId: '1:19284872025:ios:e439dcecc813db51e8da48',
    messagingSenderId: '19284872025',
    projectId: 'fasum-filbert',
    storageBucket: 'fasum-filbert.firebasestorage.app',
    iosBundleId: 'com.example.fasumFilbert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8-_ignWjW0I70fR-MeSGcmIBe9BlKD48',
    appId: '1:19284872025:web:ab6ea510cd9ae2e9e8da48',
    messagingSenderId: '19284872025',
    projectId: 'fasum-filbert',
    authDomain: 'fasum-filbert.firebaseapp.com',
    storageBucket: 'fasum-filbert.firebasestorage.app',
    measurementId: 'G-WVDHTE8TTY',
  );

}